---
services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./linode.haidar.dk.pem:/etc/ssl/linode.haidar.dk.pem
      - ./linode.haidar.dk.key:/etc/ssl/linode.haidar.dk.key
    ports:
      - 4000:80
      - 443:443
    depends_on:
      - web
    networks:
      - proxy_web
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - proxy_web
      - web_db
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - web_db
volumes:
  pgdata:
networks:
  proxy_web:
  web_db:
