FROM node:18-alpine
ARG DB_CONNECTION_STRING
ARG ORIGIN
WORKDIR /app
COPY . .
RUN npm ci
EXPOSE 3000
ENV NODE_ENV=production
ENV DB_CONNECTION_STRING=$DB_CONNECTION_STRING
ENV ORIGIN=$ORIGIN
CMD sh seed-db-and-run.sh
