---
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: always
    ports:
      - 4000:80
    depends_on:
      - web
    networks:
      - nginx_web
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - nginx_web
      - web_db
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - web_db
volumes:
  pgdata:
networks:
  nginx_web:
  web_db:
